// 塔罗牌库：78 张（22 大阿卡纳 + 56 小阿卡纳）
// 每张牌含：name 中文名、en 英文、icon 牌面图标、upright 正位解读、reversed 逆位解读

export const TAROT_DECK = [
  // ── 大阿卡纳 Major Arcana ──
  { name: '愚者', en: 'The Fool', icon: '🃏', upright: '全新开始、自由与冒险的召唤', reversed: '鲁莽、犹豫或迷失方向' },
  { name: '魔术师', en: 'The Magician', icon: '🪄', upright: '创造力与行动力，万事俱备', reversed: '才华错用、自我怀疑' },
  { name: '女祭司', en: 'The High Priestess', icon: '🌙', upright: '直觉、潜意识的智慧', reversed: '忽视内心声音、秘密未明' },
  { name: '皇后', en: 'The Empress', icon: '🌿', upright: '丰饶、滋养与温柔的力量', reversed: '依赖过度或创造力受阻' },
  { name: '皇帝', en: 'The Emperor', icon: '👑', upright: '秩序、权威与稳定', reversed: '控制欲强或缺乏自律' },
  { name: '教皇', en: 'The Hierophant', icon: '📜', upright: '传统、信仰与导师指引', reversed: '墨守成规或反叛权威' },
  { name: '恋人', en: 'The Lovers', icon: '💞', upright: '爱、契合与重要抉择', reversed: '失衡、分歧或犹豫不决' },
  { name: '战车', en: 'The Chariot', icon: '🛡️', upright: '意志驱动、突破前进', reversed: '失控、方向分散' },
  { name: '力量', en: 'Strength', icon: '🦁', upright: '柔韧的勇气与自我掌控', reversed: '自我怀疑、情绪失控' },
  { name: '隐士', en: 'The Hermit', icon: '🏮', upright: '独处、内省与求索', reversed: '孤立或逃避现实' },
  { name: '命运之轮', en: 'Wheel of Fortune', icon: '🎡', upright: '转机、命运流转', reversed: '波折、失控的变动' },
  { name: '正义', en: 'Justice', icon: '⚖️', upright: '公平、因果与清醒判断', reversed: '偏颇、逃避责任' },
  { name: '倒吊人', en: 'The Hanged Man', icon: '🙃', upright: '暂停、换视角看世界', reversed: '无谓牺牲或抗拒改变' },
  { name: '死神', en: 'Death', icon: '💀', upright: '结束与重生，放下方能前行', reversed: '抗拒结束、停滞不前' },
  { name: '节制', en: 'Temperance', icon: '🫗', upright: '平衡、调和与耐心', reversed: '极端、失衡或急躁' },
  { name: '恶魔', en: 'The Devil', icon: '😈', upright: '束缚、欲望与执念', reversed: '挣脱枷锁、觉醒' },
  { name: '高塔', en: 'The Tower', icon: '🗼', upright: '突发的崩塌与真相', reversed: '免于灾祸或拖延的危机' },
  { name: '星星', en: 'The Star', icon: '⭐', upright: '希望、疗愈与指引', reversed: '信心动摇、迷惘' },
  { name: '月亮', en: 'The Moon', icon: '🌕', upright: '幻象、直觉与潜意识', reversed: '迷雾散去、看清真相' },
  { name: '太阳', en: 'The Sun', icon: '☀️', upright: '喜悦、成功与光明', reversed: '短暂阴霾、过度乐观' },
  { name: '审判', en: 'Judgement', icon: '📯', upright: '觉醒、复盘与召唤', reversed: '自我批判、错失契机' },
  { name: '世界', en: 'The World', icon: '🌍', upright: '圆满、达成与整合', reversed: '未竟之事、收尾拖延' },

  // ── 小阿卡纳：权杖 Wands（火 · 行动）──
  { name: '权杖王牌', en: 'Ace of Wands', icon: '🔥', upright: '灵感迸发、新计划启程', reversed: '热情熄灭、拖延' },
  { name: '权杖二', en: 'Two of Wands', icon: '🌅', upright: '规划、远望与抉择', reversed: '犹豫、恐惧未知' },
  { name: '权杖三', en: 'Three of Wands', icon: '⛵', upright: '拓展、等待成果', reversed: '受阻、计划搁浅' },
  { name: '权杖四', en: 'Four of Wands', icon: '🎉', upright: '安稳、庆祝与归属', reversed: '动荡、缺乏根基' },
  { name: '权杖五', en: 'Five of Wands', icon: '⚔️', upright: '竞争、混乱中的历练', reversed: '内耗、无谓争执' },
  { name: '权杖六', en: 'Six of Wands', icon: '🏆', upright: '胜利、认可与声望', reversed: '落空的自负、延迟的荣誉' },
  { name: '权杖七', en: 'Seven of Wands', icon: '🛡️', upright: '坚守、捍卫立场', reversed: '被压垮、放弃阵地' },
  { name: '权杖八', en: 'Eight of Wands', icon: '💨', upright: '迅速推进、消息传来', reversed: '迟滞、错失时机' },
  { name: '权杖九', en: 'Nine of Wands', icon: '🩹', upright: '警惕、接近终点', reversed: '疲惫、防御过度' },
  { name: '权杖十', en: 'Ten of Wands', icon: '📦', upright: '负重前行、责任在肩', reversed: '卸下重担、懂得取舍' },
  { name: '权杖侍从', en: 'Page of Wands', icon: '🌱', upright: '好奇、热忱的探索', reversed: '三分钟热度' },
  { name: '权杖骑士', en: 'Knight of Wands', icon: '🐎', upright: '勇敢、疾风般行动', reversed: '冲动、半途而废' },
  { name: '权杖王后', en: 'Queen of Wands', icon: '🔆', upright: '自信、温暖而有魅力', reversed: '自我中心或缺乏安全感' },
  { name: '权杖国王', en: 'King of Wands', icon: '👑', upright: '远见、鼓舞他人的领袖', reversed: '专断、好大喜功' },

  // ── 小阿卡纳：圣杯 Cups（水 · 情感）──
  { name: '圣杯王牌', en: 'Ace of Cups', icon: '💧', upright: '爱意涌动、情感新生', reversed: '情感封闭、错失温柔' },
  { name: '圣杯二', en: 'Two of Cups', icon: '🤝', upright: '联结、相知与默契', reversed: '疏离、不对等的关系' },
  { name: '圣杯三', en: 'Three of Cups', icon: '🥂', upright: '欢聚、友谊与庆祝', reversed: '小圈子的排挤或过度社交' },
  { name: '圣杯四', en: 'Four of Cups', icon: '🌫️', upright: '倦怠、对现状失去兴味', reversed: '重新审视、重新接纳' },
  { name: '圣杯五', en: 'Five of Cups', icon: '💧', upright: '失落、盯着空杯叹息', reversed: '释怀、看见剩下的美好' },
  { name: '圣杯六', en: 'Six of Cups', icon: '🍬', upright: '怀旧、纯真与馈赠', reversed: '沉溺过去、不愿长大' },
  { name: '圣杯七', en: 'Seven of Cups', icon: '🌈', upright: '幻想、选择过多而迷惘', reversed: '落地、看清现实' },
  { name: '圣杯八', en: 'Eight of Cups', icon: '🚶', upright: '离开、寻更深的满足', reversed: '勉强留下、心已远走' },
  { name: '圣杯九', en: 'Nine of Cups', icon: '😊', upright: '愿望达成、心满意足', reversed: '虚荣、表面的满足' },
  { name: '圣杯十', en: 'Ten of Cups', icon: '🌈', upright: '圆满、家庭与归属感', reversed: '不和、理想落空' },
  { name: '圣杯侍从', en: 'Page of Cups', icon: '🐟', upright: '温柔的创意与心动', reversed: '情绪化、幼稚' },
  { name: '圣杯骑士', en: 'Knight of Cups', icon: '🕊️', upright: '浪漫、邀约与理想主义', reversed: '浮夸、言而无信' },
  { name: '圣杯王后', en: 'Queen of Cups', icon: '🫧', upright: '共情、温柔而通透', reversed: '情绪淹没、过度敏感' },
  { name: '圣杯国王', en: 'King of Cups', icon: '🌊', upright: '情绪稳定、包容的智者', reversed: '压抑情感、冷暴力' },

  // ── 小阿卡纳：宝剑 Swords（风 · 思维）──
  { name: '宝剑王牌', en: 'Ace of Swords', icon: '⚡', upright: '清明、真相与突破', reversed: '混乱、误用的锋利' },
  { name: '宝剑二', en: 'Two of Swords', icon: '🙈', upright: '纠结、不愿面对', reversed: '逃避无门、被迫抉择' },
  { name: '宝剑三', en: 'Three of Swords', icon: '💔', upright: '心碎、分离的痛', reversed: '疗愈开始、释怀' },
  { name: '宝剑四', en: 'Four of Swords', icon: '🛌', upright: '休憩、养精蓄锐', reversed: '无法安睡、焦躁' },
  { name: '宝剑五', en: 'Five of Swords', icon: '🌬️', upright: '得不偿失的争执', reversed: '和解、放下输赢' },
  { name: '宝剑六', en: 'Six of Swords', icon: '🚣', upright: '过渡、带着伤离去', reversed: '困在原地、难以抽身' },
  { name: '宝剑七', en: 'Seven of Swords', icon: '🤫', upright: '机变、走捷径', reversed: '被看穿、自欺' },
  { name: '宝剑八', en: 'Eight of Swords', icon: '🕸️', upright: '自我设限、看似被困', reversed: '破局、看清出路' },
  { name: '宝剑九', en: 'Nine of Swords', icon: '😟', upright: '焦虑、深夜的忧思', reversed: '释然、不再内耗' },
  { name: '宝剑十', en: 'Ten of Swords', icon: '🌑', upright: '终结、触底后的清零', reversed: '缓过劲来、避免最坏' },
  { name: '宝剑侍从', en: 'Page of Swords', icon: '🗡️', upright: '敏锐、求知的探询', reversed: '多嘴、冲动发言' },
  { name: '宝剑骑士', en: 'Knight of Swords', icon: '🌀', upright: '果断、疾速直击要害', reversed: '鲁莽、不顾后果' },
  { name: '宝剑王后', en: 'Queen of Swords', icon: '❄️', upright: '理性、清醒而独立', reversed: '苛刻、冷峻伤人' },
  { name: '宝剑国王', en: 'King of Swords', icon: '🧠', upright: '公正、智识的权威', reversed: '专制、巧言令色' },

  // ── 小阿卡纳：星币 Pentacles（土 · 物质）──
  { name: '星币王牌', en: 'Ace of Pentacles', icon: '🪙', upright: '机会、踏实的新起点', reversed: '错失机遇、根基不稳' },
  { name: '星币二', en: 'Two of Pentacles', icon: '⚖️', upright: ' juggling、灵活平衡', reversed: '顾此失彼、失衡' },
  { name: '星币三', en: 'Three of Pentacles', icon: '🧱', upright: '协作、扎实的进展', reversed: '配合失调、敷衍' },
  { name: '星币四', en: 'Four of Pentacles', icon: '🔒', upright: '守护、稳健持守', reversed: '吝啬、紧抓不放' },
  { name: '星币五', en: 'Five of Pentacles', icon: '❄️', upright: '匮乏、寒夜中的艰难', reversed: '转机、走出低谷' },
  { name: '星币六', en: 'Six of Pentacles', icon: '🤲', upright: '给予、互惠与平衡', reversed: '施舍心态、不对等' },
  { name: '星币七', en: 'Seven of Pentacles', icon: '🌱', upright: '耕耘、等待回报', reversed: '焦躁、未见成效' },
  { name: '星币八', en: 'Eight of Pentacles', icon: '🔨', upright: '钻研、精益求精', reversed: '敷衍、低质量重复' },
  { name: '星币九', en: 'Nine of Pentacles', icon: '🍇', upright: '独立、丰盈的成果', reversed: '依赖、表面的富足' },
  { name: '星币十', en: 'Ten of Pentacles', icon: '🏡', upright: '长久、家族与安稳', reversed: '散财、根基动摇' },
  { name: '星币侍从', en: 'Page of Pentacles', icon: '🌰', upright: '好学、务实的起点', reversed: '拖延、眼高手低' },
  { name: '星币骑士', en: 'Knight of Pentacles', icon: '🐂', upright: '稳健、一步一脚印', reversed: '迟钝、错失节奏' },
  { name: '星币王后', en: 'Queen of Pentacles', icon: '🌻', upright: '务实、温暖而丰足', reversed: '过度操劳、忽略自己' },
  { name: '星币国王', en: 'King of Pentacles', icon: '🏔️', upright: '可靠、富足的掌舵者', reversed: '贪婪、守财' },
]

// 三张时间牌阵的槽位标签
export const TAROT_POSITIONS = ['过去', '现在', '未来']
